Update README for Ubuntu python3-setproctitle
Launching this from Ubuntu caused:

```
~/.local/lib/python3.6/site-packages/gpt python3 run.py                 
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import modules
  File "/home/kevin/.local/lib/python3.6/site-packages/gpt/modules.py", line 24, in <module>
    import setproctitle
ModuleNotFoundError: No module named 'setproctitle'
```

Adding the missing dependency `python3-setproctitle` to Ubuntu README.